--SELECT TABLE_NAME FROM USER_TABLES;
CREATE TABLE USER_TABLE(
ID NUMBER CONSTRAINT PK1_USER_TABLE PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(500) NOT NULL
);

CREATE SEQUENCE USER_TABLE_SEQ START WITH 1000 INCREMENT BY 10;